### PR TITLE
Load Files

### PR DESCRIPTION
**Pull request by Infro**
Very hacky, but lets users load files from their device and easily switch between them.

### CODE REVIEW

**Comment by Infro** [comment]
Hasn't been tested, but hopefully works.  Will be very ugly, but is good enough for me on my phone while on the treadmill/elliptical.  Will be slowly adding more functionality with voice recognition and other things.

**Comment by amitmerchant1990** [comment]
Thanks! I'll take a look at this. 👍

**Comment by amitmerchant1990** [comment]
@Infro I tested it and looks like it's working alright but can you polish it a little bit? I can't actually merge this PR with the current state of UI. I want it to be in line with the existing UI.

**Comment by amitmerchant1990** [comment]
I'm closing this PR. Please raise a new PR after the suggested improvements.

**Pull request closed without merging**
